[package]
name = "chappy"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"] 

[dependencies]
futures = "0.3.25"
nix = "0.26.1"
prost = "0.11.6"
tokio = { version = "1.24.2", features = ["macros", "rt", "rt-multi-thread"] }
tokio-stream = "0.1.11"
tonic = "0.8.3"
tower = "0.4.13"
lazy_static = "1.4.0"
libloading = "0.7.4"
log = "0.4.17"
env_logger = "0.10.0"
ipnet = "2.7.1"
rand = "0.8.5"



[build-dependencies]
cbindgen = "0.24.3"
tonic-build = "0.8.3"
