[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9090"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8080"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7070"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307


# Databend Query ClickHouse HTTP Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8124

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8000

tenant_id = "test_tenant"
cluster_id = "test_cluster"

[log]
level = "INFO"
dir = "/tmp/logs"

[meta]
# To enable embedded meta-store, set address to ""
embedded_dir = "/tmp/meta"
address = "0.0.0.0:9191"
username = "root"
password = "root"
client_timeout_in_second = 60

# Storage config.
[storage]
type = "fs"

# fs storage.
[storage.fs]
data_path = "/tmp/data"
