version: "3.9"
services:
  clickhouse_standalone:
    build:
      context: .
      dockerfile: standalone.Dockerfile
    image: cloudfuse-io/l12n:clickhouse
    cap_drop:
      - ALL
    read_only: true
    user: nobody
    volumes:
      - clickhouse-tmp:/tmp
    entrypoint:
      # - bash
      - python3
      - lambda-handler.py
    environment:
      - AWS_ACCESS_KEY_ID=$LAMBDA_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$LAMBDA_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$LAMBDA_SESSION_TOKEN
      - AWS_REGION=$L12N_AWS_REGION
      - DATA_BUCKET_NAME
    ulimits:
      nofile:
        soft: 1024
        hard: 1024

  clickhouse_distributed:
    build:
      context: ../..
      dockerfile: docker/clickhouse/distributed.Dockerfile
    image: cloudfuse-io/l12n:clickhouse-distributed
    # unfortunately local tests of distributed images is not supported yet


volumes:
  clickhouse-tmp:
