version: "3.9"
services:
  lambdacli:
    build:
      context: ../..
      dockerfile: docker/cli/Dockerfile
      target: lambda
    image: cloudfuse-io/l12n:lambdacli
    cap_drop:
      - ALL
    read_only: true
    user: nobody
    environment:
      - AWS_ACCESS_KEY_ID=$LAMBDA_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$LAMBDA_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$LAMBDA_SESSION_TOKEN
      - L12N_AWS_REGION
      - L12N_PLUGINS=lambdaric
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
