name: Lambdatized Engines
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  engine:
    strategy:
      matrix:
        engine_name: [spark, dremio, databend, dask, trino, ballista, clickhouse]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CLI
        run: |
          L12N_BUILD=1 ./l12n-shell
      - name: Build Engine
        run: |
          COMPOSE_FILE=docker/${{ matrix.engine_name }}/docker-compose.yaml
          ./l12n-shell l12n build-images --compose-file=$COMPOSE_FILE

  branch-protection:
    needs:
      - engine
    if: always()
    runs-on: ubuntu-latest
    name: Branch Protection
    steps:
      - name: Failure
        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
        run: |
          # This check runs after any other job failed.
          exit 1
      - name: Success
        run: |
          # This check runs after all other jobs are done or skipped
          exit 0
