name: Ballista
on:
  workflow_dispatch:
    inputs:
      fork:
        required: true
        description: The for of arrow-ballista to use (e.g. apache or cloudfuse-io)
      ballista-ref:
        required: true
        description: Branch, tag or SHA to checkout (e.g. 0.9.0)


jobs:
  build:
    name: Ballista release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: '${{ github.event.inputs.fork }}/arrow-ballista'
          ref: ${{ github.event.inputs.ballista-ref }}
      - name: Dependencies
        run: |
          sudo apt-get -y install \
            libssl-dev \
            openssl \
            zlib1g \
            zlib1g-dev \
            libpq-dev \
            cmake \
            protobuf-compiler \
            curl \
            unzip
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
      - name: Cargo build
        run: cargo build --features "flight-sql s3" --release --bin ballista-scheduler --bin ballista-executor --bin ballista-cli
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.fork }}-ballista-${{ github.event.inputs.ballista-ref }}
          body: Plain build of the ${{ github.event.inputs.ballista-ref }} ref of Ballista
          files: |
            target/release/ballista-scheduler
            target/release/ballista-executor
            target/release/ballista-cli
