name: L12N
on:
  push_main:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-docker:
    name: Docker
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: CLI
        run: |
          L12N_BUILD=1 ./l12n-shell
