name: "Style Check"
on: pull_request
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Black
        run: |
          pip install --upgrade black
          black --check --diff --include "(\\.pyi?|\\.ipynb)$" --exclude "" .

      - name: isort
        run: |
          pip install --upgrade isort
          isort . -c

      - name: yamllint
        run: |
          pip install --upgrade yamllint
          git ls-files '*.yaml' '.yml' | xargs yamllint

      - name: Terraform fmt
        run: |
          terraform fmt -check -recursive -diff

      - name: Markdown Lint
        run: |
          npm install --no-save markdownlint-cli
          npx markdownlint --ignore node_modules .
