name: "Style Check"
on: pull_request
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Black
        run: |
          pip install --upgrade black
          # Note: black fails when it doesn't have to do anything.
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/main HEAD) |
            grep -v '\(\.json\|\.csv\|\.ipynb\|\.hpp\.in\|\.ref\|\.example\|\.txt\|\.lock\|\.js\)$' |
            2>/dev/null xargs black || true
          git diff --exit-code

      - name: yamllint
        run: |
          pip install --upgrade yamllint
          git ls-files '*.yaml' '.yml' | xargs yamllint

      - name: Terraform fmt
        run: |
          terraform fmt -check -recursive -diff

      - name: Markdown Lint
        run: |
          npm install --no-save markdownlint-cli
          npx markdownlint --ignore node_modules .
