name: Trino
on:
  workflow_dispatch:
    inputs:
      trino-version:
        required: true
        description: The Trino version (e.g. 378), should be compatible with the patch


jobs:
  build:
    name: Trino Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'cloudfuse-io/trino'
          ref: ${{ github.event.inputs.trino-version }}-patch
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Build
        run: ./mvnw -pl core/trino-main,core/trino-server clean install -DskipTests
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: trino-server-${{ github.event.inputs.trino-version }}
          body: Custom build of Trino Server version ${{ github.event.inputs.trino-version }} disabling file descriptor checks
          files: core/trino-server/target/trino-server-${{ github.event.inputs.trino-version }}.tar.gz
